// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-closet-items.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-closet-items.ts
var list_closet_items_default = defineTool({
  name: "list_closet_items",
  title: "List closet items",
  description: "List the signed-in user's saved clothing items, newest first. Optionally filter by category.",
  inputSchema: {
    category: z.enum(["topwear", "bottomwear", "outerwear", "footwear", "accessory"]).optional().describe("Only return items in this category."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum items to return.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clothing_items").select("id,name,brand,category,price,selected_color,selected_size,colors,sizes,image_url,product_url,fit_score,created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-closet-item.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var add_closet_item_default = defineTool2({
  name: "add_closet_item",
  title: "Add closet item",
  description: "Save a clothing item to the signed-in user's virtual closet.",
  inputSchema: {
    name: z2.string().trim().min(1).describe("Product name."),
    brand: z2.string().trim().optional().describe("Brand name."),
    category: z2.enum(["topwear", "bottomwear", "outerwear", "footwear", "accessory"]).describe("Clothing category."),
    price: z2.string().trim().optional().describe('Price with currency symbol, e.g. "$49".'),
    image_url: z2.string().url().optional().describe("Product image URL."),
    product_url: z2.string().url().optional().describe("Retailer product page URL."),
    selected_color: z2.string().trim().optional().describe("Chosen color."),
    selected_size: z2.string().trim().optional().describe('Chosen size, e.g. "M".')
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("clothing_items").insert({ ...input, user_id: ctx.getUserId() }).select("id,name,brand,category,selected_size,selected_color").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added "${data.name}" to the closet (id ${data.id}).` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/list-outfits.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var list_outfits_default = defineTool3({
  name: "list_outfits",
  title: "List outfits",
  description: "List the signed-in user's saved outfits with their layered clothing items.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20).describe("Maximum outfits to return.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("outfits").select(
      "id,name,created_at,outfit_items(layer_order,clothing_items(id,name,brand,category,selected_color,selected_size,image_url))"
    ).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { outfits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-outfit.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z4 } from "npm:zod@^3.25.76";
var create_outfit_default = defineTool4({
  name: "create_outfit",
  title: "Create outfit",
  description: "Create a named outfit for the signed-in user from existing closet item ids, layered in the given order.",
  inputSchema: {
    name: z4.string().trim().min(1).describe("Outfit name."),
    clothing_item_ids: z4.array(z4.string().uuid()).min(1).max(12).describe("Closet item ids, ordered from innermost to outermost layer.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, clothing_item_ids }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: outfit, error } = await supabase.from("outfits").insert({ name, user_id: ctx.getUserId() }).select("id,name").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = clothing_item_ids.map((clothing_item_id, index) => ({
      outfit_id: outfit.id,
      clothing_item_id,
      layer_order: index
    }));
    const { error: itemsError } = await supabase.from("outfit_items").insert(rows);
    if (itemsError) {
      return { content: [{ type: "text", text: itemsError.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Created outfit "${outfit.name}" (id ${outfit.id}) with ${rows.length} items.` }],
      structuredContent: { outfit, item_count: rows.length }
    };
  }
});

// src/lib/mcp/tools/get-measurements.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.3";
var get_measurements_default = defineTool5({
  name: "get_measurements",
  title: "Get body measurements",
  description: "Get the signed-in user's profile: display name, country, fit preference, and body measurements used for fit scoring.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("display_name,country,fit_preference,height,weight,chest,waist,hips").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-try-ons.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z5 } from "npm:zod@^3.25.76";
var list_try_ons_default = defineTool6({
  name: "list_try_ons",
  title: "List virtual try-ons",
  description: "List the signed-in user's saved virtual try-on images, newest first.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).default(20).describe("Maximum try-ons to return.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("try_ons").select("id,outfit_id,outfit_name,size,image_url,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { try_ons: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ckngfrlnsqwqxhxtiwkt";
var mcp_default = defineMcp({
  name: "ai-style-lab",
  title: "AI Style Lab",
  version: "0.1.0",
  instructions: "Tools for OUTFYT / AI Style Lab, a virtual try-on and outfit styling app. Read the signed-in user's virtual closet, outfits, body measurements, and saved try-on images; add items to the closet; and compose outfits from closet items. All data is scoped to the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_closet_items_default, add_closet_item_default, list_outfits_default, create_outfit_default, get_measurements_default, list_try_ons_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
